### ISSUE TITLE
같이가는 길에 당신이 있어 고맙습니다

### ISSUE THREAD

**Issue by joft-ware** [cyw320712/clean-code-java#1]
손 잡아 준다고 
넘어지지 않은 건 아니지만
손 내미는 당신이 고맙습니다.
 
응원한다고
삶이 힘들지 않은 건 아니지만
힘 내라는 당신이 고맙습니다. 
 
혼자 간다고
다 길 잃은 건 아니지만
기다려 준 당신이 고맙습니다.
 
말 한마디 안 한다고
우울해지는 건 아니지만
말 건네 준 당신이 고맙습니다.
 
멋진 당신처럼
고마운 분이 있기에
우리들의 삶은
더욱 아름답고 향기롭습니다.
 
오늘도
내 삶에 고마운 일
내 삶에 고마운 분
가슴속에 심으며
고마움을 함께하는
행복한 하루 되시길...

**Comment by cyw320712** [comment]
??????

**Comment by joft-ware** [comment]
감사합니다.

**Comment by joft-ware** [comment]
가난한 내가
아름다운 나타샤를 사랑해서
오늘밤은 푹푹 눈이 나린다

나타샤를 사랑은 하고
눈은 푹푹 날리고
나는 혼자 쓸쓸히 앉어 소주를 마신다
소주를 마시며 생각한다
나타샤와 나는
눈이 푹푹 쌓이는 밤 흰 당나귀 타고
산골로 가자 출출이 우는 깊은 산골로 가 마가리에 살자

눈은 푹푹 나리고
나는 나타샤를 생각하고
나타샤가 아니 올 리 없다
언제 벌써 내 속에 고조곤히 와 이야기한다
산골로 가는 것은 세상한테 지는 것이 아니다
세상 같은 건 더러워 버리는 것이다

눈은 푹푹 나리고
아름다운 나타샤는 나를 사랑하고
어데서 흰 당나귀도 오늘밤이 좋아서 응앙응앙 울을 것이다
